// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xnmmkxzkufcflkexhqlw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhubW1reHprdWZjZmxrZXhocWx3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzOTc2MDEsImV4cCI6MjA3MTk3MzYwMX0.YT9-_E5iJ76USOpAgJ0sSXWQRwyF9YmmqFfPD8Rfbng";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});